# Generated by Django 4.1.2 on 2023-02-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
